/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import model.De;

/**
 *
 * @author csnd2320
 */
public class WindowsDeviner extends javax.swing.JFrame {
private De de;
private int compteur; 

    public WindowsDeviner() {
        initComponents();
        this.de= new De(100);
        this.compteur=0;
        this.de.lancer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldValeur = new javax.swing.JTextField();
        LabelTitre = new javax.swing.JLabel();
        LabelQuestion = new javax.swing.JLabel();
        btnValidation = new javax.swing.JButton();
        LabelRésultat = new javax.swing.JLabel();
        Rejouer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextFieldValeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldValeurActionPerformed(evt);
            }
        });

        LabelTitre.setText("Bienvenue sur le jeu du dé à deviner");

        LabelQuestion.setText("Quelle est la valeur du dé ?");

        btnValidation.setText("Essayer !");
        btnValidation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidationActionPerformed(evt);
            }
        });

        LabelRésultat.setToolTipText("");

        Rejouer.setText("Rejouer");
        Rejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejouerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(LabelTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(TextFieldValeur)
                            .addComponent(btnValidation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rejouer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(LabelRésultat, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LabelTitre)
                .addGap(114, 114, 114)
                .addComponent(LabelQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValidation)
                .addGap(18, 18, 18)
                .addComponent(Rejouer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelRésultat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldValeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldValeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldValeurActionPerformed

    private void btnValidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidationActionPerformed
      String lavaleurutilisateur = TextFieldValeur.getText();
      int lavaleurde = this.de.getValeur(); 
       int lavaleurutilisateurs = Integer.parseInt(lavaleurutilisateur);
        this.compteur= this.compteur+1;
       
       if (lavaleurutilisateurs< lavaleurde){
          this.LabelRésultat.setText("C'est plus grand");
      }
      else if (lavaleurutilisateurs> lavaleurde){
        this.LabelRésultat.setText("C'est plus petit");
     
      }
      else{
          this.LabelRésultat.setText("C'est Gagné, en "+ this.compteur+ " tentatives");
          this.btnValidation.setEnabled(false);
      
      }
      
// TODO add your handling code here:
    }//GEN-LAST:event_btnValidationActionPerformed

    private void RejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejouerActionPerformed
        this.de.lancer();
        this.btnValidation.setEnabled(true);
        this.LabelRésultat.setText("Vous commencer une nouvelle partie que le sort vous soit favorable");
        this.compteur=0;
        // TODO add your handling code here:
    }//GEN-LAST:event_RejouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowsDeviner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowsDeviner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowsDeviner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowsDeviner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowsDeviner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelQuestion;
    private javax.swing.JLabel LabelRésultat;
    private javax.swing.JLabel LabelTitre;
    private javax.swing.JButton Rejouer;
    private javax.swing.JTextField TextFieldValeur;
    private javax.swing.JButton btnValidation;
    // End of variables declaration//GEN-END:variables
}
